-- 001 — multiple entries per day + threads
--
-- STATUS: DRAFT. Not executed. Verify every assumption below against the live
-- Supabase schema before running any of it. Written from README's schema summary
-- (`diaries (id, user_id, date, content, is_record_only, emotion_*, created_at, updated_at)`)
-- and from src/lib/diary.ts, which addresses rows exclusively by (user_id, date).
--
-- Why: `Diary`'s identity is currently the (user_id, date) pair, so a second entry
-- on the same day overwrites the first, and a thread has nothing stable to attach to.
-- See docs/PRODUCT_DIRECTION.md ("Schema implications").


-- ---------------------------------------------------------------------------
-- Step 0 — inspect before touching anything
-- ---------------------------------------------------------------------------
-- Run these first; the statements further down assume specific answers.
--
--   select column_name, data_type, is_nullable
--     from information_schema.columns
--    where table_schema = 'public' and table_name = 'diaries'
--    order by ordinal_position;
--
--   select conname, pg_get_constraintdef(oid)
--     from pg_constraint
--    where conrelid = 'public.diaries'::regclass;
--
-- Two things to confirm:
--   (a) does `id` already exist, and is it already the primary key?
--   (b) what is the *type* of user_id (text vs uuid)? The new tables must match it.
--       NextAuth JWT subs are strings, so `text` is the likely answer — but check.


-- ---------------------------------------------------------------------------
-- Step 1 — diaries: `id` becomes the identity, (user_id, date) stops being unique
-- ---------------------------------------------------------------------------

-- 1a. Ensure an id column exists and is populated.
alter table public.diaries
  add column if not exists id uuid not null default gen_random_uuid();

-- 1b. Promote it to primary key. ONLY run if step 0 showed the PK is not already `id`.
--     Replace the constraint name with the one step 0 printed.
-- alter table public.diaries drop constraint diaries_pkey;
-- alter table public.diaries add primary key (id);

-- 1c. Remove whatever enforces one-entry-per-day. Name comes from step 0;
--     it may be a unique constraint or a unique index.
-- alter table public.diaries drop constraint if exists diaries_user_id_date_key;
-- drop index if exists public.diaries_user_id_date_key;

-- 1d. `date` is now an ordinary attribute — it still needs an index, because every
--     read path filters by user and orders by date (sidebar groups, calendar dots).
create index if not exists diaries_user_date_idx
  on public.diaries (user_id, date desc, created_at desc);

-- 1e. Title, generated by the same AI call that does emotion analysis.
--     Nullable: existing rows have none, and record-only entries may never get one.
alter table public.diaries
  add column if not exists title text;


-- ---------------------------------------------------------------------------
-- Step 2 — threads
-- ---------------------------------------------------------------------------
-- One thread per diary entry (kind='diary'), or a standalone thread with no entry
-- (kind='question'). diary_id is nullable for exactly that reason.
-- NOTE: change user_id's type here if step 0 said it is uuid, not text.

create table if not exists public.threads (
  id          uuid primary key default gen_random_uuid(),
  user_id     text not null,
  diary_id    uuid references public.diaries(id) on delete cascade,
  kind        text not null check (kind in ('diary', 'question')),
  title       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint threads_diary_kind_ck check (
    (kind = 'diary'    and diary_id is not null) or
    (kind = 'question' and diary_id is null)
  )
);

-- Sidebar ordering: newest activity first, per user.
create index if not exists threads_user_updated_idx
  on public.threads (user_id, updated_at desc);

-- A diary entry has at most one thread.
create unique index if not exists threads_diary_uniq
  on public.threads (diary_id) where diary_id is not null;


-- ---------------------------------------------------------------------------
-- Step 3 — messages
-- ---------------------------------------------------------------------------
-- `parts` holds tool-call results (the payload the emotion cards render from).
-- Keeping it separate from `content` means a generative-UI message is not forced
-- to pretend it is text.

create table if not exists public.messages (
  id          uuid primary key default gen_random_uuid(),
  thread_id   uuid not null references public.threads(id) on delete cascade,
  role        text not null check (role in ('user', 'assistant', 'system')),
  content     text not null default '',
  parts       jsonb,
  created_at  timestamptz not null default now()
);

-- The only read pattern: one thread's messages in order.
create index if not exists messages_thread_created_idx
  on public.messages (thread_id, created_at);


-- ---------------------------------------------------------------------------
-- Step 4 — RLS
-- ---------------------------------------------------------------------------
-- The app reaches Supabase with SUPABASE_SERVICE_ROLE_KEY from server code only,
-- which bypasses RLS. Check whether `diaries` has RLS enabled today and mirror that
-- choice on the new tables rather than inventing a different one:
--
--   select relname, relrowsecurity from pg_class
--    where relname in ('diaries', 'threads', 'messages');
--
-- If the public demo route ever reads with the anon key, these tables need real
-- policies first. Do not ship a demo route that leaks other users' threads.


-- ---------------------------------------------------------------------------
-- Rollback
-- ---------------------------------------------------------------------------
-- drop table if exists public.messages;
-- drop table if exists public.threads;
-- alter table public.diaries drop column if exists title;
-- drop index if exists public.diaries_user_date_idx;
-- Restoring one-entry-per-day also requires deleting duplicate rows first:
--   alter table public.diaries add constraint diaries_user_id_date_key unique (user_id, date);


-- ---------------------------------------------------------------------------
-- Application changes this forces (src/lib/diary.ts)
-- ---------------------------------------------------------------------------
-- Every function there addresses rows by (user_id, date) and must move to id:
--   getDiary(userId, date)              -> getDiaryById(userId, id)
--                                          + listDiariesByDate(userId, date)
--   saveDiary(...)                      -> createDiary(...) / updateDiary(id, ...)
--                                          (the existing "does it exist? update : insert"
--                                           branch disappears — the caller now knows)
--   deleteDiary(userId, date)           -> deleteDiary(userId, id)
--   updateDiaryEmotion(userId, date, e) -> updateDiaryEmotion(userId, id, e)
--   analyzeAndStoreEmotion(...)         -> same, keyed by id
--
-- Routes: /diary/[date] -> /diary/[id]; /api/diary/[date] -> /api/diary/[id].
-- Keep a date-based *list* endpoint — the calendar and sidebar filter still need it.
